// examples/vite-svelte/src/App.svelte
<script lang="ts">
	import svelteLogo from './assets/svelte.svg';
	import Dragons from './components/Dragons.svelte';
	import viteLogo from '/vite.svg';
	import { QueryClient, QueryClientProvider } from '@tanstack/svelte-query';

	const queryClient = new QueryClient();
</script>

<main>
	<QueryClientProvider client={queryClient}>
		<div>
			<a href="https://vitejs.dev" target="_blank" rel="noreferrer">
				<img src={viteLogo} class="logo" alt="Vite Logo" />
			</a>
			<a href="https://svelte.dev" target="_blank" rel="noreferrer">
				<img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
			</a>
		</div>
		<h1>Vite + Svelte + WunderGraph</h1>

		<div class="card">
			<Dragons />
		</div>

		<p class="read-the-docs">Click on the Vite and Svelte logos to learn more</p>
	</QueryClientProvider>
</main>

<style>
	.logo {
		height: 6em;
		padding: 1.5em;
		will-change: filter;
		transition: filter 300ms;
	}
	.logo:hover {
		filter: drop-shadow(0 0 2em #646cffaa);
	}
	.logo.svelte:hover {
		filter: drop-shadow(0 0 2em #ff3e00aa);
	}
	.read-the-docs {
		color: #888;
	}
</style>

// examples/vite-solidjs/src/App.tsx
import './App.css';
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query';
import type { Component } from 'solid-js';
import { createQuery } from './lib/wundergraph';

const queryClient = new QueryClient();

const Dragons: Component = () => {
	const dragons = createQuery({
		operationName: 'Dragons',
	});
	return (
		<div class="results">
			{dragons.isLoading && <p>Loading...</p>}
			{dragons.error && <pre>Error: {JSON.stringify(dragons.error, null, 2)}</pre>}
			{dragons.data && <pre>{JSON.stringify(dragons.data, null, 2)}</pre>}
		</div>
	);
};

function App() {
	return (
		<QueryClientProvider client={queryClient}>
			<div class="App">
				<div>
					<a href="https://wundergraph.com" target="_blank">
						<img src="/wundergraph.svg" class="logo wundergraph" alt="WunderGraph logo" />
					</a>
					<a href="https://vitejs.dev" target="_blank">
						<img src="/vite.svg" class="logo" alt="Vite logo" />
					</a>
					<a href="https://www.solidjs.com/" target="_blank">
						<img src="/solid.svg" class="logo solid" alt="Solid logo" />
					</a>
				</div>
				<h1>WunderGraph + Vite + Solid</h1>
				<div class="card">
					<Dragons />
				</div>
				<p class="read-the-docs">Click on the WunderGraph, Vite and Solid logos to learn more</p>
			</div>
		</QueryClientProvider>
	);
}

export default App;
