// examples/nextjs-todos/components/TodoItem.tsx
import clsx from 'clsx';
import React, { Fragment, useState } from 'react';

import useUpdateTitleMutation from '../hooks/useUpdateTitleMutation';
import useUpdateCompleteStatusMutation from '../hooks/useUpdateCompleteStatusMutation';
import useDeleteTodoMutation from '../hooks/useDeleteTodoMutation';
import { Todo } from '../types';

interface TodoItemProps {
	todo: Todo;
}

function TodoItem(props: TodoItemProps) {
	const { todo } = props;
	const editTodoTitle = useUpdateTitleMutation();
	const updateCompleteTodo = useUpdateCompleteStatusMutation();
	const deleteTodo = useDeleteTodoMutation();
	const [title, setTitle] = useState<string>(todo.title);
	const [completed, setCompleted] = useState<boolean>(todo.completed);
	const [editMode, setEditMode] = useState<boolean>(false);

	function updateCompletedStatus(e: React.ChangeEvent<HTMLInputElement>) {
		let newCheckedStatus: boolean = e.target.checked;
		setCompleted(newCheckedStatus);
		updateCompleteTodo.trigger({ id: todo.id, complete: newCheckedStatus }, { throwOnError: false });
	}

	function deleteTodoItem() {
		deleteTodo.trigger({ id: todo.id }, { throwOnError: false });
	}

	function editTodoTile() {
		if (title.trim().length > 0) {
			clearEdit();
			editTodoTitle.trigger({ id: todo.id, title }, { throwOnError: false });
		}
	}

	function clearEdit() {
		setEditMode(false);
	}

	function resetTitle() {
		setTitle(todo.title);
	}

	async function titleKeyHandler(event: React.KeyboardEvent<HTMLInputElement>) {
		if (event.key === 'Escape') {
			clearEdit();
			resetTitle();
		} else if (event.key === 'Enter') {
			await editTodoTile();
		}
	}

	function enableEditMode() {
		setEditMode(true);
	}

	return (
		<Fragment>
			{!editMode && (
				<div className="flex justify-between pt-4 pb-2 m-2 px-2 w-72 hover:bg-zinc-600 hover:rounded-md last-of-type:border-0">
					<Fragment>
						<div className="flex items-center mb-1 mx-1">
							<input
								onChange={updateCompletedStatus}
								type="checkbox"
								checked={completed}
								className="h-4 w-4 rounded-full accent-pink-500"
							/>
							<div
								onDoubleClick={enableEditMode}
								className={clsx(
									['cursor-pointer ml-3 text-sm font-medium text-gray-300'],
									[completed && 'line-through']
								)}
							>
								<span className="break-all">{title}</span>
							</div>
						</div>
						<div onClick={deleteTodoItem} className="flex flex-col justify-start ml-5 cursor-pointer">
							<svg
								xmlns="http://www.w3.org/2000/svg"
								fill="none"
								viewBox="0 0 24 24"
								strokeWidth={1.5}
								stroke="#fafafa"
								className="w-5 h-5 hover:bg-zinc-500 hover:rounded"
							>
								<path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
							</svg>
						</div>
					</Fragment>
				</div>
			)}
			{editMode && (
				<Fragment>
					<div className="relative">
						<input
							type="text"
							onKeyDown={titleKeyHandler}
							value={title}
							onChange={(e) => setTitle(e.target.value)}
							className={clsx(
								[completed && 'line-through', editMode && 'mb-1'],
								'py-3 pl-10 pr-2 ml-2 h-12 border-solid  w-72 text-sm bg-zinc-500 rounded text-white focus:outline-none '
							)}
						/>
						<div
							onClick={editTodoTile}
							className="absolute right-4 top-3.5 cursor-pointer hover:bg-zinc-500 hover:rounded"
						>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								fill="none"
								viewBox="0 0 24 24"
								strokeWidth={1.5}
								stroke="white"
								className="w-5 h-5"
							>
								<path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
							</svg>
						</div>
					</div>
				</Fragment>
			)}
		</Fragment>
	);
}

export default TodoItem;

// examples/sveltekit-todos/src/lib/components/TodoItem.svelte
<script lang="ts">
	import CheckIcon from './CheckIcon.svelte';
	import XIcon from './XIcon.svelte';
	import { clickOutside, handleEnterOrEscKey } from './actions/handleKeyboardEvents';
	import { deleteTodoMutation, editTodoMutation, toggleCompleteTodoMutation } from './hooks/todos';

	export let todo: {
		id: number;
		title: string;
		completed: boolean;
		order: number;
	};

	const deleteMutation = deleteTodoMutation();
	const editMutation = editTodoMutation();
	const toggleCompleteMutation = toggleCompleteTodoMutation();

	let title = todo.title;
	let editMode = false;
	function enableEditMode() {
		editMode = true;
	}
	function disableEditMode() {
		title = todo.title;
		editMode = false;
	}
	async function updateCompletedStatus() {
		await $toggleCompleteMutation.mutate({ id: todo.id, complete: !todo.completed });
	}
	async function deleteTodoItem() {
		await $deleteMutation.mutate({ id: todo.id });
	}
	async function editTodoTile() {
		await $editMutation.mutate({ id: todo.id, title });
		disableEditMode();
	}
</script>

<div
	class="group flex justify-between items-center py-3 my-2 pl-2 pr-1 w-72 h-11 transition hover:bg-slate-800 rounded-md relative"
	class:bg-slate-800={editMode}
>
	{#if !editMode}
		<div class="flex flex-1 items-center mx-1">
			<input
				on:change={updateCompletedStatus}
				type="checkbox"
				checked={todo.completed}
				class="h-4 w-4 rounded-full transition cursor-pointer accent-pink-500 border-gray-500 bg-slate-800 text-pink-600 focus:ring-pink-500 focus:ring-1 focus:border-pink-500 hover:ring-1 focus:ring-offset-0 hover:border-pink-500 ring-pink-500"
			/>
			<div
				on:dblclick={enableEditMode}
				class="flex-1 cursor-pointer ml-3 text-sm font-medium text-gray-300"
				class:line-through={todo.completed}
			>
				<span class="break-all">{todo.title}</span>
			</div>
		</div>
		<button
			on:click={deleteTodoItem}
			class="flex-col items-center justify-center ml-5 h-9 w-9 transition cursor-pointer hidden group-hover:flex text-white opacity-50 hover:opacity-100 hover:bg-gray-700 rounded"
		>
			<XIcon />
		</button>
	{:else}
		<div class="relative w-full" use:clickOutside on:outclick={disableEditMode}>
			<input
				type="text"
				use:handleEnterOrEscKey
				on:escapeKey={disableEditMode}
				on:enterKey={editTodoTile}
				bind:value={title}
				class="py-2.5 pl-8 pr-2 h-11 -mt-[1px] border-0 w-full leadig-0 text-sm font-medium bg-slate-800 rounded text-white focus:outline-none focus:border-0 focus:ring-0"
			/>
			<button
				on:click={editTodoTile}
				class="absolute transition right-0 top-1 -mt-[1px] h-9 w-9 flex items-center justify-center cursor-pointer hover:bg-gray-700 rounded text-white"
				class:opacity-40={todo.title.trim().length === 0}
			>
				<CheckIcon className="w-6 h-6" />
			</button>
		</div>
	{/if}
</div>
